# -*- coding: utf-8 -*-
"""Project 2 DS066.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16HdhptgLN5orqef0PV6lNzvKNG7qHsXD

Project 2

Reg_no: DS066
"""

import pandas as pd

df = pd.read_csv('https://raw.githubusercontent.com/Tiamiyu1/Python-for-Data-Science-and-Analytics/main/Data/store_data.csv')

df

"""1. Which store has the highest total sales for the final month of data?"""

df.tail(4)

df.tail(4).sum()

"""Store A has the highest total sales for the final month of data"""



"""2.Which store makes the most sales on average?"""

df.mean()

"""Store B makes the most sales on average"""



"""3.Which store sells the most during the week of March 13th, 2016?"""

df[df['week'] =='2016-03-13']

"""Store D sells the most during the week of March 13th, 2016"""



"""4. In what week does store C make its worst sales?"""





"""5.Which store has the most sales in the latest 3-month period?"""

df.tail(12)

df.tail(12).sum()

"""Store A has the most sales in the latest 3-month period"""

